test_sample.py을 pytest로 실행했을떄, 오류 메세지를 보여준다 왜냐하면 func(3)는 5를 출력하지 않다.

test_sysexit.py을 pytest 실행했을때, 아무 오류 없이 실행된다.

테스트 함수에 tmpdir를 쓰면 pytest에서 검색을해서 fixture factory를 호출하여
테스트 함수 호출을 수행하기 전에 resource를 생성한다.
test_tmpdir.py을 pytest로 실행했을때, AssertionError가 뜬다.
